# 5.4 Instructions
import io
from ...opcode import InstructionBase, Nop, Unreachable
from typing import Dict, List, Type


opcode_table: Dict[int, Type[InstructionBase]] = {
    # 5.4.1 Control Instructions
    0x00: Unreachable,
    0x01: Nop,
    0x02: Unreachable,
    0x03: Unreachable,
    0x04: Unreachable,
    0x05: Unreachable,
    0x06: Unreachable,
    0x07: Unreachable,
    0x08: Unreachable,
    0x09: Unreachable,
    0x0A: Unreachable,
    0x0B: Unreachable,
    0x0C: Unreachable,
    0x0D: Unreachable,
    0x0E: Unreachable,
    0x0F: Unreachable,
    0x10: Unreachable,
    0x11: Unreachable,

    # 5.4.2 Parametric Instructions
    0x1A: Unreachable,
    0x1B: Unreachable,

    # 5.4.3 Variable Instructions
    0x20: Unreachable,
    0x21: Unreachable,
    0x22: Unreachable,
    0x23: Unreachable,
    0x24: Unreachable,

    # 5.4.4 Memory Instructions
    0x28: Unreachable,
    0x29: Unreachable,
    0x2A: Unreachable,
    0x2B: Unreachable,
    0x2C: Unreachable,
    0x2D: Unreachable,
    0x2E: Unreachable,
    0x2F: Unreachable,
    0x30: Unreachable,
    0x31: Unreachable,
    0x32: Unreachable,
    0x33: Unreachable,
    0x34: Unreachable,
    0x35: Unreachable,
    0x36: Unreachable,
    0x37: Unreachable,
    0x38: Unreachable,
    0x39: Unreachable,
    0x3A: Unreachable,
    0x3B: Unreachable,
    0x3C: Unreachable,
    0x3D: Unreachable,
    0x3E: Unreachable,
    0x3F: Unreachable,
    0x40: Unreachable,

    # 5.4.5 Numeric Instructions
    # const instructions
    0x41: Unreachable,
    0x42: Unreachable,
    0x43: Unreachable,
    0x44: Unreachable,
    # other numeric instructions
    0x45: Unreachable,
    0x46: Unreachable,
    0x47: Unreachable,
    0x48: Unreachable,
    0x49: Unreachable,
    0x4A: Unreachable,
    0x4B: Unreachable,
    0x4C: Unreachable,
    0x4D: Unreachable,
    0x4E: Unreachable,
    0x4F: Unreachable,

    0x50: Unreachable,
    0x51: Unreachable,
    0x52: Unreachable,
    0x53: Unreachable,
    0x54: Unreachable,
    0x55: Unreachable,
    0x56: Unreachable,
    0x57: Unreachable,
    0x58: Unreachable,
    0x59: Unreachable,
    0x5A: Unreachable,

    0x5B: Unreachable,
    0x5C: Unreachable,
    0x5D: Unreachable,
    0x5E: Unreachable,
    0x5F: Unreachable,
    0x60: Unreachable,

    0x61: Unreachable,
    0x62: Unreachable,
    0x63: Unreachable,
    0x64: Unreachable,
    0x65: Unreachable,
    0x66: Unreachable,

    0x67: Unreachable,
    0x68: Unreachable,
    0x69: Unreachable,
    0x6A: Unreachable,
    0x6B: Unreachable,
    0x6C: Unreachable,
    0x6D: Unreachable,
    0x6E: Unreachable,
    0x6F: Unreachable,
    0x70: Unreachable,
    0x71: Unreachable,
    0x72: Unreachable,
    0x73: Unreachable,
    0x74: Unreachable,
    0x75: Unreachable,
    0x76: Unreachable,
    0x77: Unreachable,
    0x78: Unreachable,

    0x79: Unreachable,
    0x7A: Unreachable,
    0x7B: Unreachable,
    0x7C: Unreachable,
    0x7D: Unreachable,
    0x7E: Unreachable,
    0x7F: Unreachable,
    0x80: Unreachable,
    0x81: Unreachable,
    0x82: Unreachable,
    0x83: Unreachable,
    0x84: Unreachable,
    0x85: Unreachable,
    0x86: Unreachable,
    0x87: Unreachable,
    0x88: Unreachable,
    0x89: Unreachable,
    0x8A: Unreachable,

    0x8B: Unreachable,
    0x8C: Unreachable,
    0x8D: Unreachable,
    0x8E: Unreachable,
    0x8F: Unreachable,
    0x90: Unreachable,
    0x91: Unreachable,
    0x92: Unreachable,
    0x93: Unreachable,
    0x94: Unreachable,
    0x95: Unreachable,
    0x96: Unreachable,
    0x97: Unreachable,
    0x98: Unreachable,

    0x99: Unreachable,
    0x9A: Unreachable,
    0x9B: Unreachable,
    0x9C: Unreachable,
    0x9D: Unreachable,
    0x9E: Unreachable,
    0x9F: Unreachable,
    0xA0: Unreachable,
    0xA1: Unreachable,
    0xA2: Unreachable,
    0xA3: Unreachable,
    0xA4: Unreachable,
    0xA5: Unreachable,
    0xA6: Unreachable,

    0xA7: Unreachable,
    0xA8: Unreachable,
    0xA9: Unreachable,
    0xAA: Unreachable,
    0xAB: Unreachable,
    0xAC: Unreachable,
    0xAD: Unreachable,
    0xAE: Unreachable,
    0xAF: Unreachable,
    0xB0: Unreachable,
    0xB1: Unreachable,
    0xB2: Unreachable,
    0xB3: Unreachable,
    0xB4: Unreachable,
    0xB5: Unreachable,
    0xB6: Unreachable,
    0xB7: Unreachable,
    0xB8: Unreachable,
    0xB9: Unreachable,
    0xBA: Unreachable,
    0xBB: Unreachable,
    0xBC: Unreachable,
    0xBD: Unreachable,
    0xBE: Unreachable,
    0xBF: Unreachable,
}

def read_instructions(stream: io.RawIOBase) -> List[InstructionBase]:
    return []
